"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Status:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Status.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OK: _Status.ValueType  # 0
    IMAGE_SIZE_MISMATCH: _Status.ValueType  # 1
    ERROR: _Status.ValueType  # 2

class Status(_Status, metaclass=_StatusEnumTypeWrapper):
    """enum 定義"""

OK: Status.ValueType  # 0
IMAGE_SIZE_MISMATCH: Status.ValueType  # 1
ERROR: Status.ValueType  # 2
global___Status = Status

@typing.final
class DataRequest(google.protobuf.message.Message):
    """リクエスト: 可変長の byte 列"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYLOAD_FIELD_NUMBER: builtins.int
    payload: builtins.bytes
    def __init__(
        self,
        *,
        payload: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["payload", b"payload"]) -> None: ...

global___DataRequest = DataRequest

@typing.final
class DataResponse(google.protobuf.message.Message):
    """レスポンス: ステータス"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: global___Status.ValueType
    def __init__(
        self,
        *,
        status: global___Status.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___DataResponse = DataResponse
