# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_server.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'image_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12image_server.proto\x12\x0cimage_server\"\x1e\n\x0b\x44\x61taRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"4\n\x0c\x44\x61taResponse\x12$\n\x06status\x18\x01 \x01(\x0e\x32\x14.image_server.Status*4\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x17\n\x13IMAGE_SIZE_MISMATCH\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x32P\n\x0b\x44\x61taService\x12\x41\n\x08SendData\x12\x19.image_server.DataRequest\x1a\x1a.image_server.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=122
  _globals['_STATUS']._serialized_end=174
  _globals['_DATAREQUEST']._serialized_start=36
  _globals['_DATAREQUEST']._serialized_end=66
  _globals['_DATARESPONSE']._serialized_start=68
  _globals['_DATARESPONSE']._serialized_end=120
  _globals['_DATASERVICE']._serialized_start=176
  _globals['_DATASERVICE']._serialized_end=256
# @@protoc_insertion_point(module_scope)
